config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'questions#index'
  root to: "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions do
    resources :answers
    resources :question_categorys
    #resources :categorys, only: :index
    collection do
      get 'search'
    end
  end
  resources :categorys do
    resources :questions, only: :index
  end
  #get 'questions' => 'questions#index_category'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :question_categorys, dependent: :destroy
  has_many :categorys, through: :question_categorys

  validates :content, presence: true
  validates :title, presence: true

  #validate :add_error
 
  #def add_error

  #  if title.blank?
  #    errors[:base] << "タイトルを入力してください"
  #  end

  #  if content.blank?
  #    errors[:base] << "質問を入力してください"
  #  end

  #end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_category

  def index
    #csv出力用と一覧表示用のcategory_idがある
    @category = params[:csv_category_id] || params[:category_id]
    if @category
      @mycategory = Category.find(@category)
      @questions = @mycategory.questions.includes(:user).order("created_at DESC")
    else
      ##n+1問題解決のために色々試したが解決せず。
      #@questions = Question.all.order("created_at DESC")
      #以下の記述だとbulletでn+1問題が検出されない。この書き方でいいのかな
      @questions = Question.includes(:user).order("created_at DESC")
      #@questions = Question.includes(:user).includes(:categorys).order("created_at DESC")
      #@questions = Question.includes(:user).includes(:categorys).each{|question| p question.categorys.name}
      #@questions = Question.includes(:categorys).order("created_at DESC")
      #@questions = Question.includes(:user, {categorys: :question_categorys}).order("created_at DESC")
      #@questions = Question.includes(:user).includes(categorys: :question_categorys).order("created_at DESC")
      #binding.pry
    end
    respond_to do |format|
      format.html
      format.csv { send_data render_to_string, type: :csv, filename: "questions_category.csv" }
    end
  end

  def search
    @questions = Question.where('title LIKE(?)', "%#{params[:keyword]}%").order("created_at DESC")
    respond_to do |format|
      format.html {render action: :index}
      format.json
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
    else
      if @question.content.blank?
        flash.now[:content] = '質問を入力してください。'
      end
      if @question.title.blank?
        flash.now[:title] = 'タイトルを入力してください。'
      end
      @questions = Question.all.order("created_at DESC")
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    question = Question.find(params[:id])
    question.update(question_params)
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.all.includes(:user)
  end

  def set_category
    @categorys = Category.all
  end

  private
  def question_params
    #params.require(:question).permit(:title, :content, { :category_ids => [] }).merge(user_id: current_user.id)
    params.require(:question).permit(:title, :content, category_ids: [] ).merge(user_id: current_user.id)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def show_category(instance)
    categorys = instance.categorys.all
    html_text = ''
    categorys.each do |category|
      html_text += link_to "#{category.name} ", "/categorys/#{category.id}/questions"
    end
    return html_text.html_safe
  end

  def edit_link(instance)
    link_to 'edit', edit_question_path(instance), method: 'get'
  end

  def delete_link(instance)
    link_to 'delete', "/questions/#{instance.id}", method: 'delete'
  end

  def show_link(instance)
    link_to 'answer', question_path(instance), method: 'get'
  end

  def buttons_link(instance)
    if @path.is('questions#index', 'questions#search')
      content_tag(:ul, class: 'functions-btns__btn') do
        if current_user_has?(instance)
          concat content_tag(:li, edit_link(instance), class: 'functions-btns__btn__edit')
          concat content_tag(:li, delete_link(instance), class: 'functions-btns__btn__delete')
        end
        if user_signed_in?
          concat content_tag(:li, show_link(instance), class: 'functions-btns__btn__show')
        end
      end
    end
  end

end

app/views/questions/_answer.html.haml
.question
  .container
    .container__upper-info
      .container__upper-info__title
        回答
      .container__upper-info__questioner
        =answer.user.name
    .container__middle-info
      %p.container__text
        =answer.response
    .functions-btns
      %ul.functions-btns__btn
        %li.functions-btns__btn__edit
          edit
        %li.functions-btns__btn__delete
          delete

app/views/questions/_category.html.haml
.category
  //=link_to category_path(category.id) do
  =link_to category_questions_path(category.id) do
    =category.name

app/views/questions/_header.html.haml
.header
  %h2.title
    %a{href: root_path} qweet
  %form{action: "/questions/search", method: "get"}
    %ul.search
      %li.search__content
        %input{name: "keyword", size: "15", id: "search__query"}
      %li.search__content
        %input{type: "submit", value: "検索"}
  %form{action: questions_path(format: :csv), method: "get"}
    %ul.search
      %li.search__content
        %input{type: "submit", value: "csv出力"}
        %input{type: "hidden", name: "csv_category_id", value: @category}
  %ul.nav
    -if user_signed_in?
      %li.nav__content
        =current_user.name
      %li.nav__content
        =link_to "質問する", new_question_path, method: 'get'
      %li.nav__content
        =link_to "ログアウト", destroy_user_session_path, method: 'delete'
        //=button_to "ログアウト", destroy_user_session_path, method: 'delete'
        //=link_to "ログアウト", destroy_user_session_path, method: 'get'
        //%form{action: "/users/sign_out", method: "delete"}
        //  %input{type: "submit", value: "ログアウト"}
    -else
      %li.nav__content
        =link_to "新規登録", new_user_registration_path, method: 'post'
      %li.nav__content
        =link_to "ログイン", new_user_session_path, method: 'get'
    %li.nav__content
      =link_to "カテゴリ登録", new_category_path, method: 'get'

app/views/questions/_notifications.html.haml
.notification
  %p
    - flash.each do |key, value|
      = content_tag :div, value, class: key
  //- question.errors.full_messages.each do |message|
  //  = message
  //  %br/

app/views/questions/_question.html.haml
.question
  .container
    .container__upper-info
      .container__upper-info__title
        =question.title
      .container__upper-info__questioner
        =question.user.name
    .container__category-info
      =show_category(question)
      //以下三行をまとめた
      //-question.categorys.each do |category|
      //  =link_to category_questions_path(category.id) do
      //    =category.name
    .container__middle-info
      %p.container__middle-info__text
        =question.content
    .functions-btns
      =buttons_link(question)
//以下の記述内容を一行に収めることで見通しを良くした。
-#
      -if @path.is('questions#index', 'questions#search')
        %ul.functions-btns__btn
          -if current_user_has?(question)
            %li.functions-btns__btn__edit
              = link_to 'edit', edit_question_path(question), method: 'get'
            %li.functions-btns__btn__delete
              = link_to 'delete', "/questions/#{question.id}", method: 'delete'
          -if user_signed_in?
            %li.functions-btns__btn__show
              = link_to 'answer', question_path(question), method: 'get'
-#

app/views/questions/create.html.haml
.wrapper
  .new-edit-question
    %h2 登録しました
    %br/
    =link_to "一覧に戻る", root_path

app/views/questions/destroy.html.haml
.wrapper
  .new-edit-question
    %h2 削除しました
    %br/
    =link_to "一覧に戻る", root_path

app/views/questions/edit.html.haml
.wrapper
  .new-edit-question
    %h2 修正フォーム
    %br/
    = form_for @question do |f|
      タイトル
      %br/
      = f.text_field :title
      %br/
      質問内容
      %br/
      = f.text_area :content, size: "40x5"
      %br/
      = f.submit "Send"
      %br/
      %br/
      =link_to "一覧に戻る", root_path

app/views/questions/index.html.haml
.wrapper.clearfix
  = render partial: 'header'
  .contents.clearfix
    .content-left
      //= render 'notifications', locals: { question: @question }
      = render 'notifications'
      = render partial: 'question', collection: @questions
    .content-right
      .categorys
        = render partial: 'category', collection: @categorys

app/views/questions/new.html.haml
.wrapper
  = render partial: 'notifications', locals: { question: @question }
  .new-edit-question
    %h2 登録フォーム
    %br/
    = form_for @question do |f|
      タイトル
      %br/
      = f.text_field :title
      %br/
      質問内容
      %br/
      = f.text_area :content, size: "40x5"
      %br/
      カテゴリー
      %br/
      = f.collection_check_boxes :category_ids, Category.all, :id, :name
      %br/
      = f.submit "Send"
      %br/
      %br/
      =link_to "一覧に戻る", root_path

app/views/questions/show.html.haml
.wrapper.clearfix
  = render partial: 'header'
  .contents.clearfix
    .content-left
      = render partial: 'notifications'
      = render partial: "question", locals: { question: @question }
      .question
        .container
          %h2 登録フォーム
          = form_for [@question, @answer] do |f|
            %br/
            回答内容
            %br/
            = f.text_area :response, size: "40x5", class: "textarea"
            %br/
            = f.submit "Send", id: "button"
      = render partial: "answer", collection: @answers
    .content-right
      .categorys
        = render partial: 'category', collection: @categorys

app/views/questions/update.html.haml
.wrapper
  .new-edit-question
    更新しました
    =link_to "一覧に戻る", root_path